### ISSUE TITLE
valdr-enabled

### ISSUE THREAD

**Issue by venki0552** [netceteragroup/valdr#112]
```
  <div class="col-xs-6">
   <div valdr-form-group  valdr-enabled="isValdrEnabled()">
       <select  placeholder="Select"  class="textField" data-ng-model="input.select1"
        ng-options="type.name as type.value for type in array">
              <selected  value="">Select</option>
       </select>
    </div>
    <div valdr-form-group class="width100">
        <select name="type" textField" data-ng-model="input.select2"
                 data-ng-options="type.name as type.value for type in types">
            <option  selected  value="">Select</option>
        </select>
    </div>
 </div>
```

When I am using valdr enabled like this I am not getting validation message for select2 but red border is applied for select2.
Note: If I focus on it then its displaying the error message properly.
Please let me if am using wrongly.

**Comment by JakePartusch** [comment]
I believe that you will need to specify the `valdr-enabled` attribute for each `vald-form-group` attribute. Either that, or move the `valdr-enabled` to the parent `div` element

**Comment by venki0552** [comment]
Only to that particular field i need validation to be conditional so I think there is no need to apply valdr-enabled to all the other inputs.

**Comment by alexkhismatulin** [comment]
+1
@venki0552 have you found a solution?

**Comment by B8li** [comment]
@alexkhismatulin 
Can you please check the following link:
https://plnkr.co/edit/8wVpmQhIH3GAp0mkFCov?p=preview

There `valdr-enabled` is used conditionally based on the checkbox selection.

Note: Also make sure that you've included `valdr-message.js` script.

**Comment by alexkhismatulin** [comment]
hey @B8li found out that actually problem was not in valdr, it works fine. My own directive caused additional validation. Anyway, thanks for response!
