### ISSUE TITLE
Display of validation message in tooltips

### ISSUE THREAD

**Issue by nishadk123** [netceteragroup/valdr#118]
Is there a way to display the validation messages similar to facebook rather than just below the inputs?

![Facebook registration](https://cdn-images-1.medium.com/max/800/1*mQtZw4fQMGw_yMylgU0kuQ.png)

**Comment by marcelstoer** [comment]
Take note of https://github.com/netceteragroup/valdr#support and study https://github.com/netceteragroup/valdr#showing-validation-messages-with-valdr-messages
