### ISSUE TITLE
valdr-message throws "Possible unhandled rejection..." in Angular 1.6: $translate promise rejection not handled

### ISSUE THREAD

**Issue by christophercr** [netceteragroup/valdr#121]
The updateTranslations() function inside the valdrMessage directive uses the $translate service to get some translations. This call return a Promise which can be either resolved or rejected. Obviously the function just cares about the successful result, which is handled, however the rejection is not handled.

This is now being thrown as an error in Angular 1.6+ by default (see https://code.angularjs.org/1.6.4/docs/api/ng/provider/$qProvider)

**Comment by christophercr** [comment]
@philippd, @marcelstoer  Could you maybe have a look on this?

**Comment by B8li** [comment]
@christophercr, PR is looks good and it's merge. Thx for fixing the issue.
