### ISSUE TITLE
Make validation conditional 

### ISSUE THREAD

**Issue by bonce164** [netceteragroup/valdr#54]
Hi, I really like your library but I would really like to be able to dynamically enable/disable the validation based upon some other model value. e.g.

`<div valdr-form-group valdr-enabled="vm.isLive === true">`
`<input id="onlyValidateWhenLive" name="onlyValidateWhenLive" type="text" />`
`</div>`

I couldn't find a way of passing model values to a custom validator which would be my preferred method.

**Comment by philippd** [comment]
@bonce164 it's now released in 1.1.1
