### ISSUE TITLE
Radio validation?

### ISSUE THREAD

**Issue by glook** [netceteragroup/valdr#61]
Hello, i didn't find any information about checkbox or radio validation, how to validate it?

**Comment by marcelstoer** [comment]
Show us (part of) your HTML form and the JavaScript and we may be able to help you. Also, note that [support requests are best handled on StackOverflow](https://github.com/netceteragroup/valdr#support).

**Comment by philippd** [comment]
The only validation rule I can think of for checkboxes and radios is ```required```. I'd suggest to just use the AngularJS directives for this and use valdr for all other types of form items.
