### ISSUE TITLE
Behavior of error message?

### ISSUE THREAD

**Issue by Wolfr** [netceteragroup/valdr#66]
If I add my-email johan.ronsse@gmail.com to the email field of the demo, then remove the .com part, blur the field, nothing happens. Isn't it supposed to say "invalid input" in this situation?

**Comment by marcelstoer** [comment]
> Isn't it supposed to say "invalid input" in this situation?

No. The [domain part] (http://en.wikipedia.org/wiki/Email_address#Domain_part) must not necessarily be end with a TLD. However, it needs to identify a host name. `foo@localhost` is a syntactically correct email address.

Sidenote, valdr uses the same [regex for email validation](https://github.com/netceteragroup/valdr/blob/master/src/core/validators/emailValidator.js) as Angular (also see [tests](https://github.com/netceteragroup/valdr/blob/master/src/core/validators/emailValidator.spec.js)).
