### ISSUE TITLE
Please fix your bower.json

### ISSUE THREAD

**Issue by LingLong** [netceteragroup/valdr#72]
for example valdr-message should also specify maintype, if not grunt-bower-install will lose its magic and
what happens is, that on every serverstart your index.html will lose its dependencies.

**Comment by LingLong** [comment]
i refer to this stackoverflow post: http://stackoverflow.com/questions/21633247/bower-transitive-dependency-not-added-for-angular

**Comment by philippd** [comment]
Fixed with https://github.com/netceteragroup/bower-valdr/commit/a1402ebd881261910bf00a52d3611d95bfb81eda
