### ISSUE TITLE
Nested object validation

### ISSUE THREAD

**Issue by NeRo2pt0** [netceteragroup/valdr#73]
Is it possible to have more than one valdr-type within a form? Reason I am asking is because I am having a difficult time trying to get my nested object validation working.

**Comment by philippd** [comment]
Yes. You can check this example: https://github.com/netceteragroup/valdr/blob/master/demo/core/simple.html

Here the valdr-type ```Address``` is nested in ```Person```.

**Comment by NeRo2pt0** [comment]
Thanks for the quick response.  This was exactly what I was looking for :) cheers

**Comment by marcelstoer** [comment]
Also, in the future please [ask for help](https://github.com/netceteragroup/valdr#support) on Stackoverflow using the `valdr` tag rather than creating an issue here.
