### ISSUE TITLE
any known issues with UI-Router?

### ISSUE THREAD

**Issue by ohNegative** [netceteragroup/valdr#79]
Hey guys,

I'm trying to use this and I have a pretty complicated setup. I'm using ui-router and trNgGrid alongside your plugin Valdr. I'm also using partials (or partial views) for the pages and have created a single main template (index.html) and I'm running into issues getting the form validation to work correctly. I'm not getting any errors in the console, but its not working right now.

Here is the partial for the "Search" page. I'm just trying to get one field to validate before I move on to the rest of the fields:

```
<form class="form-inline" id="basicSearch" name="userForm" valdr-type="claim">
       <div class="form-group">
           <label for="claimId">Claim ID</label>
           <input type="number" name="claimID" class="form-control" id="claimId" placeholder="Claim ID" ng-model="claimID" required>  
        </div>
</form>
```

Here is the app.js file:

```
var routerApp = angular.module('routerApp', ['ui.router', 'trNgGrid', 'valdr', ]);

routerApp.config(function($stateProvider, $urlRouterProvider) {

$urlRouterProvider.otherwise('/home');

$stateProvider
    .state('home', {
        url: '/home',
        templateUrl: 'global/partials/home.html'
    })
    .state('search', {
        url: '/search',
        templateUrl: 'search/partials/search.html'
    })
    .state('intake', {
        url: '/intake',
        templateUrl: 'intake/partials/intake.html'
    })
});

routerApp.config(function(valdrProvider) {
  valdrProvider.addConstraints({
    'Claim': {
      'claimID': {
        'size': {
          'min': 8,
            'max': 10,
          'message': 'The Claim ID is 10 numbers long.'
        },
        'required': {
          'message': 'Claim ID is required.'
        }
      },
    }
});
    
});

```

Since I'm not getting any errors in the console, I figure I'm pretty close to getting this to work. Let me know if you need anymore information.

Thanks in advance.

Pete

**Comment by bjorm** [comment]
I am pretty sure the constraint names are case-sensitive, so I would give it a go with `valdr-type="Claim"`, see if that helps.

**Comment by marcelstoer** [comment]
Great you find valdr useful!

> I am pretty sure the constraint names are case-sensitive

Yes, they are. And please don't use this issue list for support requests: https://github.com/netceteragroup/valdr#support

**Comment by ohNegative** [comment]
closing and moving issue to the support link you posted.

P
