### ISSUE TITLE
make valdr open for validating non-input-select/-textarea widgets, e.g. ui-select

### ISSUE THREAD

**Issue by mmatczak** [netceteragroup/valdr#83]
valdr should support validation of non-input/-select/-textarea elements, such as ui-select.

Please consider this solution (pull request): https://github.com/netceteragroup/valdr/pull/82 which can be seen in action at: http://plnkr.co/edit/3Y8GDSB8NKqae60ckhJq?p=preview

**Comment by imamovic** [comment]
+1

**Comment by philippd** [comment]
added with dbbbd37cbc1e0510d2a56ca3362e0f7e30c1cf3b

**Comment by philippd** [comment]
Released in 1.1.3

**Comment by chillyistkult** [comment]
This is a really great addition, thank you!
