### ISSUE TITLE
valdrMessage does not add messages of angular validation directives

### ISSUE THREAD

**Issue by mmatczak** [netceteragroup/valdr#90]
The valdrMessage directive does not add messages when a custom AnglarJS validation directive is added. This happens only when this custom validation is the only validator on a field - see this plnkr for details: http://plnkr.co/edit/Og3u8FhE7HTt2EFCj03R?p=preview

The reason is the $watch not being triggered in the valdrMessage directive. I have created a pull request containing a fix: https://github.com/netceteragroup/valdr/pull/89

The plnkr also contains the fixed version of valdr-messages.js, which can be activated in the index.html, to see how it works.

**Comment by philippd** [comment]
Thanks a lot for reporting and the fix. It's merged and the fix will be released soon.

**Comment by philippd** [comment]
released in 1.1.4: https://github.com/netceteragroup/valdr/releases/tag/v1.1.4
