### ISSUE TITLE
How to add a new custom message for my custom directive using valdr

### ISSUE THREAD

**Issue by krunalsheth3** [netceteragroup/valdr#93]
I have a directive created for validating passowrd and confirm password fields The directive looks like this

.directive('compareTo', function(){
    // Runs during compile
    return {
        require: "ngModel",
                scope: {
                    otherModelValue: "=compareTo"
                },
                link: function(scope, element, attributes, ngModel) {

                    ngModel.$validators.compareTo = function(modelValue) {
                        return modelValue == scope.otherModelValue;
                    };

                    scope.$watch("otherModelValue", function() {
                        ngModel.$validate();
                    });

                }
    };
});

The link function does return me the correct boolean value, but the how do I display the error message ? The error element did show up with a red icon but the message besides it is empty. Where do I initialize this message ?

REF: http://stackoverflow.com/questions/33247745/valdr-how-to-add-a-new-message-in-using-valdr

**Comment by marcelstoer** [comment]
Tracking in SO is enough. This issue list is for bug reports and feature requests.

**Comment by krunalsheth3** [comment]
ok Thanks.
But please can you reply on SO ?
