### ISSUE TITLE
How can i validate password & confirm password..??

### ISSUE THREAD

**Issue by nithinkrishnanp** [netceteragroup/valdr#97]
I need to to equate the password & confirm password using valdr?.. how it is possible?

**Comment by laudeon** [comment]
Hello,

According to the readme, you should create a custom valider. Here, you want to compare two fields and assert that they are equal. So, add a custom valider:

```javascript
angular.module('yourAppName').factory('sameValidator', function () {
	return {
		name: 'same',
		validate: function (value, args) {

			return value === document.querySelector('[name="'+args.as+'"]').value;
		}
	};
});
```

And use it:

```json
"password": {
      "required": {
        "message": "errors.message.required"
      }
    },
    "PasswordConfirm": {
      "required": {
        "message": "errors.message.required"
      },
      "same": {
        "as": "password",
        "message": "errors.message.sameAs"
      }
    }
```

I hope that could help!

**Comment by mbejda** [comment]
@laudeon  +1

**Comment by ganesh190589** [comment]
Hi,
  Please refer the custom validation.  Then u can validate easily

**Comment by marcelstoer** [comment]
You got the solution, thank you community members. However, this issue list is not a support forum, see https://github.com/netceteragroup/valdr#support.
