### ISSUE TITLE
minLength 

### ISSUE THREAD

**Issue by meta-akshat-mathur** [netceteragroup/valdr#99]
When i apply minLength constraint on a field then field becomes required.

**Comment by marcelstoer** [comment]
Common wisdom AFAIK is that null values are considered valid. Hence, the last two tests in https://github.com/netceteragroup/valdr/blob/master/src/core/validators/minLengthValidator.spec.js#L73 seem wrong.

**Comment by meta-akshat-mathur** [comment]
Issue arise when you entered a value in a field then delete it, but still it gives a error message for the min length is required

**Comment by marcelstoer** [comment]
Fixed with #107.
